const SHAPE_WIDTH = 100,
    SHAPE_HEIGHT = 100;
const CIRCLE_RADIUS = 5;
const SYNC_INTERVAL = 5;
const SHAPE_RADIUS = 5;

export { SHAPE_WIDTH, SHAPE_HEIGHT, CIRCLE_RADIUS, SYNC_INTERVAL, SHAPE_RADIUS };